# Generated by Django 2.2.5 on 2020-04-02 23:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Star Wars', 'Star Wars'), ('Space', 'Space'), ('Castle', 'Castle'), ('Pirate', 'Pirate'), ('City', 'City'), ('Marvel Heroes', 'Marvel Heroes'), ('DC Heroes', 'DC Heroes'), ('Harry Potter', 'Harry Potter'), ('Other', 'Other')], max_length=20)),
                ('image', models.ImageField(upload_to='LegoMyApp/')),
            ],
            managers=[
                ('LegoSets', django.db.models.manager.Manager()),
            ],
        ),
    ]
