# Generated by Django 2.2.5 on 2020-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegoMyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='category',
            field=models.CharField(blank=True, choices=[('Star Wars', 'Star Wars'), ('Space', 'Space'), ('Castle', 'Castle'), ('Pirate', 'Pirate'), ('City', 'City'), ('Marvel Heroes', 'Marvel Heroes'), ('DC Heroes', 'DC Heroes'), ('Harry Potter', 'Harry Potter'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='image',
            field=models.ImageField(blank=True, upload_to='LegoMyApp/'),
        ),
    ]
