# Generated by Django 2.2.5 on 2020-04-09 00:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('LegoMyApp', '0002_auto_20200404_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniFig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='LegoMyApp/')),
            ],
            managers=[
                ('MiniFigs', django.db.models.manager.Manager()),
            ],
        ),
    ]
